import { $, $$ } from '../dom.js';

export function getElements() {
  return {
    form: $('#calculatorForm'),
    modes: $$('input[name="mode"]'),
    unitButtons: $$('[data-unit-button]'),
    themeButtons: $$('[data-theme-button]'),
    currentUnit: $('[data-current-unit]'),
    distanceInput: $('#distanceInput'),
    paceInput: $('#paceInput'),
    timeInput: $('#timeInput'),
    gradeInput: $('#gradeInput'),
    terrainSelect: $('#terrainSelect'),
    calculateButton: $('#calculateButton'),
    resetButton: $('#resetButton'),
    copyButton: $('#copyButton'),
    shareButton: $('#shareButton'),
    resultLabel: $('#resultLabel'),
    resultBadge: $('#resultBadge'),
    mainResult: $('#mainResult'),
    subResult: $('#subResult'),
    metricPace: $('#metricPace'),
    metricSpeed: $('#metricSpeed'),
    metricDistance: $('#metricDistance'),
    metricTime: $('#metricTime'),
    projectionModel: $('#projectionModelSelect'),
    projectionBody: $('#projectionTableBody'),
    gradeInsight: $('#gradeInsight'),
    gradeExplanation: $('#gradeExplanation'),
    hrMaxInput: $('#hrMaxInput'),
    hrRestInput: $('#hrRestInput'),
    hrZonesBody: $('#hrZonesBody'),
    ltPaceInput: $('#ltPaceInput'),
    paceZonesBody: $('#paceZonesBody'),
    zonesByHr: $('#zonesByHr'),
    zonesByPace: $('#zonesByPace'),
    hrZonesPanel: $('#hrZonesPanel'),
    paceZonesPanel: $('#paceZonesPanel'),
    historyList: $('#historyList'),
    clearHistoryButton: $('#clearHistoryButton'),
  };
}
